version: '3'
services:
  grafana:
    image: grafana/grafana:5.4.3
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/config/grafana.ini:/etc/grafana/grafana.ini:ro
      # sudo mkdir -p /var/lib/grafana; chown 472:472 /var/lib/grafana
      - /var/lib/grafana:/var/lib/grafana
    networks:
      - monitoring

  victoria-metrics:
    image: valyala/victoria-metrics:tags-v1.7.2-single-image-0-gfdfc6ef9
    container_name: victoria-metrics
    ports:
      - "8428:8428"
    volumes:
      - /var/lib/victoria-metrics:/var/lib/victoria-metrics
    command:
      - "-storageDataPath=/var/lib/victoria-metrics"
      - "-memory.allowedPercent=40"
      - "-loggerLevel=INFO"
    networks:
      - monitoring




networks:
  monitoring:
    driver: bridge
